---
title: Research Resource I
author: Bui Gia Khanh
---
## Abstract

This long-term article contains all resources available and ready to be used, on the study of artificial intelligence and related concepts. 
___

## 0.I - Research Journals Collection

- [Computational Intelligence (Diana Inkpen)](https://onlinelibrary.wiley.com/journal/14678640) - _Computational Intelligence_ is an artificial intelligence journal publishing novel research on a broad range of experimental and theoretical topics in AI and computer science.
	- Coverage: Machine learning, knowledge mining, web intelligence, AI language, and philosophical implications.

## I - Research Papers Reading

1. An efficient encoder-decoder architecture with top-down attention for speech separation [Kai Li](https://arxiv.org/search/cs?searchtype=author&query=Li,+K),[Runxuan Yang](https://arxiv.org/search/cs?searchtype=author&query=Yang,+R), [Xiaolin Hu](https://arxiv.org/search/cs?searchtype=author&query=Hu,+X) - [Arxiv Paper](https://arxiv.org/abs/2209.15200)
2. Understanding How Encoder-Decoder Architectures Attend [Kyle Aitken et al.](kaitken17@gmail.com) - [Research Paper](https://proceedings.neurips.cc/paper/2021/file/ba3c736667394d5082f86f28aef38107-Paper.pdf) . 
3. Activation Functions in Deep Learning: A Comprehensive Survey and Benchmark [Shiv Ram Dubey](https://arxiv.org/search/cs?searchtype=author&query=Dubey,+S+R), [Satish Kumar Singh](https://arxiv.org/search/cs?searchtype=author&query=Singh,+S+K), [Bidyut Baran Chaudhuri](https://arxiv.org/search/cs?searchtype=author&query=Chaudhuri,+B+B) - [Arxiv Paper](https://arxiv.org/abs/2109.14545)
4. Novel mixture allocation models for topic learning - [Kamal Maanicshah](https://onlinelibrary.wiley.com/authored-by/Maanicshah/Kamal), [Manar Amayri](https://onlinelibrary.wiley.com/authored-by/Amayri/Manar), [Nizar Bouguila](https://onlinelibrary.wiley.com/authored-by/Bouguila/Nizar) - [doi.org]([https://doi.org/10.1111/coin.12641](https://doi.org/10.1111/coin.12641)). A very interesting read about topic modelling. [Wiley](https://onlinelibrary.wiley.com/doi/full/10.1111/coin.12641) and [Original Article](https://onlinelibrary.wiley.com/doi/epdf/10.1111/coin.12641). 
5. [Logic Tensor Networks](https://arxiv.org/abs/2012.13635) ([Samy Badreddine](https://arxiv.org/search/cs?searchtype=author&query=Badreddine,+S), [Artur d'Avila Garcez](https://arxiv.org/search/cs?searchtype=author&query=Garcez,+A+d), [Luciano Serafini](https://arxiv.org/search/cs?searchtype=author&query=Serafini,+L), [Michael Spranger](https://arxiv.org/search/cs?searchtype=author&query=Spranger,+M)) - First order logic and neurosymbolic treatment of neural network.
6. The Modern Mathematics of Deep Learning - [Julius Berner](https://arxiv.org/search/cs?searchtype=author&query=Berner,+J), [Philipp Grohs](https://arxiv.org/search/cs?searchtype=author&query=Grohs,+P), [Gitta Kutyniok](https://arxiv.org/search/cs?searchtype=author&query=Kutyniok,+G), [Philipp Petersen](https://arxiv.org/search/cs?searchtype=author&query=Petersen,+P) - [Arxiv](https://arxiv.org/abs/2105.04026). 
7. Towards a Mathematical Understanding of Neural Network-Based Machine Learning: what we know and what we don't - [Weinan E](https://arxiv.org/search/cs?searchtype=author&query=E,+W), [Chao Ma](https://arxiv.org/search/cs?searchtype=author&query=Ma,+C), [Stephan Wojtowytsch](https://arxiv.org/search/cs?searchtype=author&query=Wojtowytsch,+S), [Lei Wu](https://arxiv.org/search/cs?searchtype=author&query=Wu,+L) - [Arxiv](https://arxiv.org/abs/2009.10713). 

## II. Articles for Resource Reading

### IBM AI Development

- [Unsupervised learning for data classification](https://developer.ibm.com/articles/cc-unsupervised-learning-data-classification/) 
- [Tutorial on Artificial Intelligence](https://developer.ibm.com/technologies/artificial-intelligence/tutorials/)
- [What is self-supervised learning?](https://www.ibm.com/topics/self-supervised-learning#:~:text=Driven%20by%20this%20key%20difference,regression%20tasks%20typical%20to%20supervised)

###  Statistic StackExchange PL

- Which notation and why: $\text{P}()$, $\Pr()$, $\text{Prob}()$, or $\mathbb{P}()$? - [link](https://stats.stackexchange.com/questions/108441/which-notation-and-why-textp-pr-textprob-or-mathbbp).
- [How to calculate the likelihood function](https://stats.stackexchange.com/questions/132877/how-to-calculate-the-likelihood-function) - Surprisingly, this question has an answer that really, well, explain likelihood than other "answers". 
- [Statistical learning theory versus computational learning theory?](https://stats.stackexchange.com/questions/63077/statistical-learning-theory-vs-computational-learning-theory) 

### Artificial Intelligence PL

- [What is the difference between self-supervised and unsupervised learning?](https://ai.stackexchange.com/questions/40341/what-is-the-difference-between-self-supervised-and-unsupervised-learning)
- [What is self-supervised learning in machine learning?](https://ai.stackexchange.com/questions/10623/what-is-self-supervised-learning-in-machine-learning)
- [Can we Consider Regularization as a "Constraint"?](https://ai.stackexchange.com/questions/34527/can-we-consider-regularization-as-a-constraint).

___

## LXL - Lectures and Notes

### Mixed

1. https://ufal.mff.cuni.cz/~helcl/courses/npfl116/slides/03-encoder-decoder.pdf - On Encoder - Decoder Architecture. 
2. [What does PAC learning theory really mean?](https://www.baeldung.com/cs/probably-aproximately-correct)
3. [Error and Residue](https://en.wikipedia.org/wiki/Errors_and_residuals)
4. [Regression Analysis](https://en.wikipedia.org/wiki/Regression_analysis)
5. [8803 Machine Learning Theory - CMU](https://www.cs.cmu.edu/~ninamf/ML11/lect0825.pdf). 

### Mathematical Aspects of Deep Learning

Main link: [here](https://elmos.scripts.mit.edu/mathofdeeplearning/). 

### Czech Technical University in Prague DokuWiki

Main site: [link](https://cw.fel.cvut.cz/wiki/start). 

### Principles and Techniques of Data Science (UC Berkeley, Summer 2020)

- [Syllabus](https://ds100.org/su20/syllabus/)
- [Calendar](https://ds100.org/su20/calendar/)
- [Resources](https://ds100.org/su20/resources/)
- [Staff](https://ds100.org/su20/staff/)
- [Github Repository Account - Berkeley Data Science](https://github.com/DS-100)

### Cambridge MSc Advanced Study - Department of Quantum Physics and Computing

[Quantum Computation, Information and Foundations](https://www.maths.cam.ac.uk/postgrad/part-iii/prospective/preparation/resources/quantum-computation)
[Part III - Quantum Computation](https://www.qi.damtp.cam.ac.uk/part-iii-quantum-computation)
[Part IB - Quantum Mechanics](https://www.qi.damtp.cam.ac.uk/part-ib-quantum-mechanics#)
[Part II - Quantum Information and Computation](https://www.qi.damtp.cam.ac.uk/part-ii-quantum-information-and-computation)

### Anne Sabourin's Courses on Statistic and Statistical Learning

She is a professor at previously Telecom ParisTech and is now a professor in Université Paris Cité. There are many interesting, high level lecture notes and previous notes on lectures of advanced study on statistics, as well as learning theory and machine learning theory. 
- Main link: [here](https://helios2.mi.parisdescartes.fr/~asabouri/Teaching.html)

#### Present Courses

- Exploratory Data Analysis (Master's program [Mathematics and Applications (MDA), 1st year](https://math-info.u-paris.fr/en/master-in-mathematics-and-applications/) )
- Mathematical statistics, jointly with Fabienne Comte (Master's program [Mathematics and Applications (MDA)](https://math-info.u-paris.fr/en/master-in-mathematics-and-applications/) ), track IMB, 1st year
- Non Parametric Statistics (Master's program [Mathematics and Applications (MDA),](https://math-info.u-paris.fr/en/master-in-mathematics-and-applications/) 2nd year)
- High Dimensional statistics ( [master MDA](https://math-info.u-paris.fr/en/master-in-mathematics-and-applications/) , 2nd year, track MMA)
- [Statistical Learning with Extreme Values](https://helios2.mi.parisdescartes.fr/~asabouri/extremes-cours-MVA/extreme-course-MVA.html) [, master MVA](https://www.master-mva.com/cours/statistical-learning-with-extreme-values/)

#### Main Past Courses

- Survival analysis (Master's program [Mathematics and Applications (MDA), IMB track, 2nd year, Université Paris-Cité](https://math-info.u-paris.fr/en/master-in-mathematics-and-applications/) )
- Tail events analysis: Robustness, outliers and models for extreme values (Joint course with Pavlo Mozharovskyi)
- [Statistics-Linear Model, MS Big Data, MDI-720 (Telecom Paris)](https://helios2.mi.parisdescartes.fr/~asabouri/mdi720/mdi720.html)
- Extremes ( [Lecture notes](https://helios2.mi.parisdescartes.fr/~asabouri/extremes-cours/poly.pdf) ), Master's program ["Mathématiques de l'aléatoire"](http://webens.math.u-psud.fr/-Mathematiques-de-l-Aleatoire-?lang=fr), Paris-Saclay University- Orsay. 
- Numerical methods (MACS-205, Telecom ParisTech, Spring semester)
- [Introduction to Bayesian learning](https://helios2.mi.parisdescartes.fr/~asabouri/bayes-XT/bayes-course.html) , Master Data sciences, (Ecole Polytechnique, Institut polytechnique de Paris)
- [Statistics MDI-220 (Telecom Paris)](https://helios2.mi.parisdescartes.fr/~asabouri/mdi220/mdi220.html)
- Bayesian filtering (SIGMA-203-b, Telecom ParisTech, Spring semester)
- Probability MDI-104 (Telecom ParisTech, Fall semester)
- Computational statistics and optimisation, Master 'Data Science', Ecole Polytechnique. ( [Lecture notes](http://www.lix.polytechnique.fr/bigdata/mathbigdata/wp-content/uploads/2014/10/Lnotes_CvxAn_FullEn.pdf) ): Convex problems in Machine Learning, non smooth convex analysis, Fenchel-Legendre transform, duality.

### A Short Course on Nonparametric Curve Estimation - MSc in Applied Mathematics at EAFIT University (Colombia), 2017

Main links to the course: [here](https://bookdown.org/egarpor/NP-EAFIT/)

### Introduction to Programming Synthesis (MIT, Solar-Lezama)
[Lectures 1 and Main site](https://people.csail.mit.edu/asolar/SynthesisCourse/Lecture1.htm) - Overall course have 24 lectures. **Important**.

### Dive Deep into Deep Learning (Alex J. Smola et al)

Main link to source: [link](https://d2l.ai/index.html). 
This is a very important text, and is used to be the main resource for deep learning study. 

### AstroML Project

[Main page](https://www.astroml.org).
[Ridge and Lasso: Geometric Interpretation](https://www.astroml.org/book_figures/chapter8/fig_lasso_ridge.html) - Illustration on Ridge and Lasso Regularized Regression (L1 and L2). 

___

