stages:
  - deploy

pages:
  stage: deploy
  image: ghcr.io/quarto-dev/quarto-full:latest
  script:
    - quarto render core
    - mv core/public public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
  artifacts:
    paths:
      - public