---
title: "Progress update - 28th April 2026"
author: Fujimiya Amane
date: 2026/04/28
---

Well, not much as been done here. I will have to write this `readme`? Hell no. Well technically yes, it is my job. But, hell no. Well no. I guess I still have to write it? Well then forget what is there for now. Welcome back to the series of *weekly update* on how everything was going. 

But anyway, welcome to RHINALAB @ MTAIL research group. This is a great way to get going on the tagging system, and should it be so, it would be nice to inquire on such method of contingent. 

For this April, nothing much is happening, because the laboratory section is still being built and so on. Much likely, this time would be short of any development rather than building the base already established there, and should it be so, it would be a slow process rather than not. 

As far as I am considered, we are lacking manpower. So, it would be wise to trek this place carefully, I guess. 

But overall, nothing much is happening, and I am quite happy with the pace I am getting at, barring certain technological issues. Hopefully everything will go away much better, so that it would be resolved more often. 
