---
title: Welcome to  MTAIL
format:
  html:
    grid:
      body-width: 1000px
---

## Specification

As for RHINELAB tradition, we are to present the laboratory specific *classification identification*. 

### Lab type

The lab is **UNIG-1**, Universal (Scientific) Research Group. Designation follows from `DOC-OR-PROP-07` and subsequent `MNU-OR-02`. 

### Principal Investigator & Advisors & Members

- Bui Gia Khanh, RHINELAB Laboratory Director (Vietnam National University, Hanoi University of Science). 
- Luong Van Tam, Researcher and Partial Advisor (Vietnam National University, Hanoi University of Science)
- Dang Tri Trung, Researcher and Experimental Design (Monash University, Australia). Currently passive. 
- Associate Professor Nguyen Ai Viet, Advisor (IGNITE Institute, Vietnam National University).

## Introduction

This is the documentation page for many of the development of the **Modelling, Theoretical Artificial Intelligence and Learning-theoretic Group** (MTAIL) and documentation thereof. It will also include several notes and exposure of the lab itself here, including the *ranking order* framework itself (this one is under-developed, but sure, we might as well include the bare-bone), many notes and question debates, and more. First created by the necessity of purpose for reorganizing the research program into a multi-people central consensus rather than a solo-working environment, the website is minimally created to hook with the main website of the laboratory, and host all capable form of documents and writing relevant to the work that the lab group conducts itself of. 

Currently, the list of inclusion, to-do works and many requests for migration of details, build-up and so on, are listed as followed. Note that some of them are still in settlement stage.  

1. **Neural network formalism**: This one has a website, however that is right now outdated and out of control, so it should be reorganized soon so we can start. Such is to realize of the capacity of the *neural formalism* using neural units to its full interpretation, not the narrow definition taken of virtue by normal scientific approaches of the minimal neuron. 
2. **Foundational modelling theory** in construction. We are still having to migrate the contents here, especially on *encoding dependency* and the formalization of *gauge invariance* formalism beside the age-old incomprehensible stack of explanations that serve no one but misunderstanding and implicit notions. 
3. Theoretical computer science, evolution theory, theoretical learning theory (*computational learning theory*, statistical learning theory and more), mathematical theories and epistemology, with certain aspects a few fields like iterative process, simulation theories and so on are in list of construction. 
4. Question sites and justification template. So for each question, asking such requires you to form certain *line of thoughts*: justification, logic of deliverance, and then unresolved tension and specification of what the question entails, or would it give more questions to come. 

The goal would be long, and I will have to include them more in the future. But for now, I guess this is fairly enough. Further clarification would be delivered in their respective section instead, so it should worry not about said topic than the one held responsible, i.e. the group leader. 

:::{.callout-important}

Many of the contents for this website are under construction, and similarly for the wiki. We have not been able to push all the contents in research for the last two years up immediately, thus a lot would be missing. Apologize for the delay. 

For better experience viewing this website, you can try using [Dark Reader](https://darkreader.org/) as additionals for dark mode, if able. 

:::

### I. Logistical Information

Some of the below information are also supplants for other groups. Most of which would be included elsewhere nominally (for example, some on the *specification already*), but well, yes. Some of the following contents would be *outdated*, as it serves here only as a *quick gateway* into what is possible from within, and different constructions thereof. 

#### Current members

The following lists the current members of the laboratory group, for MTAIL and also potential collaborators outside. 

##### Principle researcher and leader

- 藤宮天音 (Fujimiya Amane), or *Bui Gia Khanh* - Lab leader of RHINELAB, and also **principle researcher** for MTAIL.

##### Researcher

- Luong Van Tam - Researcher, working mainly on double descent. 
- Dang Tri Trung - Researcher, working mainly on double descent and aspect inquiry on them for reinforcement learning. Currently on *passive status*[^1] [^2]

[^1]: Per usual configuration, there exists the two extremum: *passive* where the member is still in the laboratory section, but with reduced notice, effort available and commitment, however expertises and contributions upon help are still available. The other is the *active* status, where they actively contribute with major efforts of the laboratory effect. In between them is the *semi-active/passive* phase where these are balanced out, and with the consideration of *fuzzy boundary*, I guess we can make it so that gauging commitment is a rather deliberate move than not.

[^2]: So far, only **two** (2) person are responsible on active sessions for the group, with all others are collaborators or rather major additions. We are looking for people sharing our visions, as described in [Information](about.qmd). 

Past members include:

- Le Anh Thu (Vin University, Hanoi, Vietnam): Experimental Researcher, worked on designs of large system testing of double descent. 
- Daud Shahbaz (COMSAT University Islamabad, Islamabad, Pakistan): Experimental Research, worked on experimental designs and wide-testing of double descents throughout models. 

#### For the double descent and learning theory sections

Double descent is **one of the main research**, started back from the early 2024. As for current active information pages, they include mostly (this is duplicated in the main page for each respective parts of such), certain form of pre-completion drafts, such as:

- [The Universal Guideline on Artificial Automata](https://github.com/Amane-Fujimiya/UAI_Book) - still under construction, is the foremost document itself. The name is again, Amane Fujimiya or Bui Gia Khanh (as I use two names), and is more about theoretical attempts on AI theory in its entirety. So far, [this link will be the one](https://mozilla.github.io/pdf.js/web/viewer.html?file=https://raw.githubusercontent.com/Amane-Fujimiya/UAI_Book/master/A/A1.AI/A1%20-%20UAI/main.pdf) that gives you the last available rendered manuscript of the book (note that it is on the `master` branch). 
- **Main manuscript** - constructed on [This Particular Repository (TPR)](https://github.com/Amane-Fujimiya/ML_Double_Descent_Paper) of which holds from the first to the last manuscript. Current active manuscript in total is the `Draft` folder itself document. Alongside that, [this paper](https://arxiv.org/pdf/2103.05127) would form chapter 6 of the manuscript itself. The manuscript of the *Theoretical Learning manuscript* of **this project** can be found [in here](https://mozilla.github.io/pdf.js/web/viewer.html?file=https://raw.githubusercontent.com/Amane-Fujimiya/ML_Double_Descent_Paper/main/Draft/main.pdf) of its latest version. Recently, the statistical direction has been **updated** substantially, and currently intensive tests are going on. 
- The code repository includes [this one on GitHub](https://github.com/Izzie1911/DD-with-basic-model-), with its copy and extension on GitLab. The link will be routed later. 

### II. UNIG-1 - Supporting Information

:::{.callout-note}
Since RHINE@MTAIL is dedicated as an **UNIG** (Универсальная научно-исследовательская группа, or *universal scientific research group*) for RHINELAB in total, this framework is to serve as lab-based evaluation on theoretical directive and dependency ledger tasking.
:::

#### Temporary Framework: The rough ordering level


For certain purposes, the rather higher partition in the list contains another foundation group on the **theoretical theory directive**, which is the encompassing category of both the artificial intelligence group and the physics studies group right now. By category, we have the dependency or foundational order concept, which categorizes the following by order of **C(X)** for X count as the ascending level (I being the highest). By virtue of the position that *modelling precedes axiom* [^3], the inversion invites the following ladder as to be true, in a restricted form, yet nevertheless appropriate of its propensity to be taken forward:

[^3]: Of this, befitting of the goal thereof to be said, picking out structure, deciding what to represent, choosing what relationships matter - which represents the part of which modelling takes place, and of which such word gains its strength - is epistemically and ontologically prior to the formalization that axioms represent, nor the act of isolation. One can see the fact that idealization and of which universality, is the fact being compressed, of the messy world where one to controls it requires simplification, not the act to be disbanded and berated, but the delusion thereof to subsume of the reality it belongs toward. 

- Theory of modelling and the application thereof (CI). 
- Mathematical theory and encoding language research (CI). 
- Theory of computer science and automata realization (CII). 
- Practical computer instantiation consideration (CIII). 
- Physics theory and mathematical physics (CII). 
- Practical-theoretical physical gap (CIII). 
- Artificial intelligence theory (CII). 
- Artificial intelligence practical-theoretical implementation (CIII). 
- Hardware-interfaced-or-designed neural formalism network (CIII). 

And so on, with more to add on the list, and more to relinquish such description to a dedicated section rather than passing words of sketchwork. This is also to separate *dependency* layer from which later on we will expand for experiment, real system or any amount of resources for practical purposes. I.e. we will also do practical stuffs, but have to retain the order of dependency. The reasoning would have to be seen elsewhere, as it would require a series of intensive illustration, justification and overall subjective view, opinionated analysis and henceforth, much to the description being rather long and tedious, within reason of helpfulness and completeness be rather treated carefully, or of the worst outcome be the **invalidation** of efforts taken to enforce such programme. Nevertheless, such is useful, and one should also take into account why modelling is stayed on top. 

#### Updates

:::{.callout-note}

### Your local bulletin on updates. 

Since no one has taken upon this job, I figured I will. 

- 2025/09/28 - Started drafting.
- 2026/03/12 - Updated contents. 
- 2026/03/16 - Updating a few metadata. 
- 2026/04/13 - Publish the website and add a few more organizations. 
- 2026/05/06 - Updated a fair bit of contents, reorganized and updating descriptions, starting to migrate. 

:::

