# Material

Before studying anything about material science, we might as well be familiarized of the concept, and the historiography on what *material* can be constituted of. Surprisingly, or rather the unsurprising thereof, is that such concept has been presented in a very long time, ever since the old age of the Roman Empire, and further down the path. 

## The tell-tale of material ([Amelia Carolina Sparavigna, 2011](https://arxiv.org/pdf/1107.3831))

In the age of Ancient Rome, two books, the *De Architectura* by Vitruvius and *naturalis Historia* by Pliny the Elder, gives us the portrait of the material science, or the knowledge in specificity about materials, in Rome at the beginning of the Empire. In most of the case studies, it is in the making of four case studies: concretes, coatings, amorphous materials, and colloidal crystals, to describe them in the modern corpora of words. 

The word *science* itself comes from the Latin *scientia*, for which to mean "knowledge", and then, to find the material science of the past, it is natural to respond it toward the "knowledge of materials". Interestingly, such knowledge as seen of the use cases, often accompanied us within which our life interacts of it. Such is why, the question of material science in those times are not rather fundamental, but before the requirement of the body of studies, one ask:

- What are those objects? 
- Can I use them, and how can I use them? 
- What can they be used against each other? How would that work? 
- What kind of knowledge of which makes it *actionable* for which I can attain specification or purpose?

Often, the thought of the existence thereof, of being, is reserved to the philosopher as their inquiry requires a form of entanglement and in-depth observations. Though, it does not bring about much in short or medium-term of meaningful actions, such is also why typically, the equation of which we draw about material science would not include that (however, we do note such are rather useful, and would be nice to get). 

> Marcus Vitruvius Pollio lived in the 1st century BC. He was a Roman architect and engineer, best known as the author of the “De Architectura” [5]. Gaius Plinius Secundus, known as Pliny the Elder, died on 25 August, 79 AD during the eruption of Mount Vesusius. He was a Roman naturalist as well as naval commander of the Roman Empire. He wrote an encyclopaedic work, the “Naturalis Historia” [6]. These two books give us a portrait of knowledge in Rome, at the beginning of the Empire, and deserve a longer study. For instance, the “Naturalis Historia” contains several detailed descriptions of metals, pigments and precious stones.

Most observations about dust and stones thereof, started rather mundanely. 

> There is a species of sand which, naturally, possesses extraordinary qualities. It is found about Baiae and the territory in the neighbourhood of Mount Vesuvius; if mixed with lime and rubble, it hardens as well under water as in ordinary buildings. This seems to arise from the hotness of the earth under these mountains and the abundance of springs under their bases. (Vitruvius, translated)

The template of the material presentation is deliberate. Such is where the construct is typical, for Vitruvius to describe pozzolana, derived from unconsolidated pyroclastic materials, of which are now known of such name though unpacking it requires rather substantial time and evidences, erupted by the Campi Flegrei, a volcanic field near Vesuvius. The part is rather interesting - if such is mixed with lime and rubble, it hardens as well under water as in ordinary buildings. Under their civilization perspective, such is rather interesting, because it is basically a type of *constructive medium* in which can be used to build, of course, building or any form of structures. They are purely of use, and of which their description finds themselves into **where the material** can be found, and of which such context on where it is found gives rise to the interpretation on the question for *how*. Such is the same reasoning that would be met of many ancient civilizations, or even modern time of any construct with the lack of structural details, if there is any, and interpretation varies. Interestingly, Vitruvius continues telling that 

> [...] it seems certain that the moisture is extracted from the sand-stone and earth in their neighbourhood, by the strength of the fire, as from limestone in a kiln. Dissimilar and unequal actions thus concentrated towards the same end, the great want of moisture quickly supplied by water binds and strongly cements them, and also imparts a rapid solidity.

Even by then, the science of material science constitutes the knowledge on how they are manipulated of form, either by their creation on circumstances speculated, or by artificial means. The process of which describe how the material is formed, by Vitruvius' word, is rather deliberate, as to mean of a natural fabricating process. Mundane enough to extract the macroscopic properties on 'how would such operate', and why. But not enough to say all of it. In essence, the scribe describes the "dissimilar and unequal actions, concentrating the motion towards the same end, the great want of moisture quickly supplied by water binds and strongly cements them, and also imparts a rapid solidity." per the mechanism of the material. However, 

> But he notes that in Tuscany, where there are several hot springs too, “we do not there find a powder, which, for the same reason, would harden under water … All lands do not possess similar qualities; nor is stone universally found. Some lands are earthy, others gravelly, others gritty, others sandy: in short, the quality of land, in different parts of the earth, varies as much as even the climate itself.”

The model does break. Perhaps rather trivially of sort. The property of land, of which forms the basic foundational substrate where this rather *derivative form* of material can be found, varies between lands, contexts, and regions. The model is thus rather local - it might seem obvious that way, but only under some very specific circumstances that it should rather would be instantiated correctly to give such result. By description of the process, assuming the process is actualization of the real oracle in which how pozzolana is, the actualization requires many contexts of which can be known, or rather not known of, and of conditions and expectations that would happen at will. Moreover, the main assumption of the model is as to always observe the end-product to be pozzolana, of which evidently by his own words, we can take a measured stance as to be not quite. Thus, such concludes the written description of the first "hydraulic cement" in history. Such is not perfect, nor it is anywhere near what we have, but their process is the same - the model breaks under instantiation of context, works within what it describes, and of which for the details it is given, and assumptions on what observe, deliver the interpretation befit of replication to a given degree. 

Such can be said of many problems and models we currently use in history of science as to the modern time. While technology have advanced, technology in itself is the utlization of such, and thus bares the same notion in which manipulation and knowledge is rather not perfect, as to there exist many failure points one cannot expect. One can also find utilization, crude but effective way of such in Pliny's cement, of which the human industry devised even broken pottery into something else. Most of them have the virtue of the generous context. We, however, do not. 

## The modern history of material science

Due of history, material science emerged full-fledged in the USA, some time in the early 1950s. However, the period before it stems much of the context into which the current structure of material science is of present. And a fairly dirty history one can get from it. Per @ModyMartin2020_MaterialsScience for example, such is rather famously taken of a complicated history at large. 

Material science stems from, or rather inherited of the settled practices toward *what metallurgy is*, which have been in existence for a rather long period of time. During the 18th-19th centuries of the enlightenment, knowledge about materials, specifically if we are to host an operational form on what constitutes a *material*. Traditionally, material in consideration is this *solid*, but the wider range can be pointed to any form of matter in hosting all state of matters, or now so we speak. In such it also includes, obviously, foundational matters of biological one, so to speak. 

There, we gradually gain the empirical ground on metallurgy, chemistry, mechanical engineering, and industrial manufacturing. Per @cahn2001coming and @eliade1956forge, of which gives many craft knowledge and scientific investigation of the substrate itself, but not by much being the *field* of material science. That is because, there exists no middle ground on theories at that focal point, so much so material investigations were solely considered as to be the instantiation of the physical theories and thereof, most often the very general foundational theory of physics. Many would say that *material science did not exist before 1950s*, and such would be hard to refute. 

### Cold War reorganization

During the Cold War, the entire field was considered and rather transformed into being of existence, taking on specific pipelines, and body of theories starting from source materials into the actual objects. 

> Through the mid-1950s, Cold War competition focused principally on nuclear weapons development as the United States and the Soviet Union raced to amass larger and larger arsenals. But within the logic of nuclear deterrence, the delivery systems for nuclear weapons mattered just as much as the weapons themselves. A nation with powerful enough rockets could deliver a nuclear warhead to any spot it chose on the globe. The Soviet launch of the world’s first artificial satellite, Sputnik, on October 4, 1957, therefore represented a shift. The aluminium sphere’s radio blips were not as consequential as the demonstration of rocketry powerful enough to launch a satellite into space—or deliver a nuclear warhead. Some nuclear capabilities would still be based on nuclear-armed aircraft, and later submarines, but an increasing proportion of the nuclear powers’ arsenals would sit on the tip of sophisticated rockets, ready to race toward their targets at a moment’s notice.

Born out of metallurgy (for details, see @cahn2001coming), material science was considered a **superdiscipline**, as it hinges on very much the entire landscape of science at large of the moment, stretching of all apparatus, theories of all scales, and thus encompassing an unusual interdisciplinary environment condition. The reorganization of material science defines the field by modern standard as to be certainly a pluralism of details

> David Turnbull, in his illuminating Commentary on the Emergence and Evolution of “Materials Science” (Turnbull 1983), defined materials science "broadly" as "the characterisation, understanding, and control of the structure of matter at the ultramolecular level and the relating of this structure to properties (mechanical. magnetic, electrical, etc.). That is, it is 'Ultramolecular Science'."

or, in one way or another in COSMAT Report of 1974, as

> [...] concerned with the generation and application of knowledge relating the composition, structure, and processing of materials to their properties and uses.

During the mid-1950s, there existed at that time, two traditions that would rather unable to talk with one another. First, was the **industrial research sector**, exemplified by Bell Laboratories, and so forth, but not limited to of legacy, per individual empiricisms without foundation of the Bessemer process (1856), the Siemens-Martin open-hearth furnace (1860s), the Hall-Héroult aluminium process (1886). This only comes back and forth toward temporal inversion - technology precedes theory, theory then rationalizes technology - will soon be observed again pre-formation as such. Bell Lab functioned as more of an industrial research system rather than the typical conventional laboratory that you would see, operating inside a vertically integrated telecommunications monopoly that treated discovery as infrastructure, perhaps more than just some patents. The purposes were not to chase products or market timing but to solve fundamental problems that would stabilize and extend a national communication network, which in turns the monopoly money being reinvested into more foundational problem. Such created of itself an *insulating internal culture* that permits Bell Laboratory to get the transistor (1947), information theory (1948), laser partly of itself, and so on, and shield them from having to chase external peer review or annual grant cycles, nor commercially relevant products' formation. As such, we say, that *science precedes the commercial utilization*. 

The other sector was the **academic disciplinary science**, which is the traditional one where metallurgy grown out of mining engineering curricula were positioned. Working on rather a practical and empirical side, solid-state physics, ceramic engineering, polymer chemistry, and so on, they are settled, at the time, to live in separate buildings, separate departments, using only foundational physics as justification, separate conferences, trained in separate PhD programs, and all of the above. These communities were intellectually productive but siloed, and each was, in Paul Forman's phrasing, partly insulated from the guiding hand of physics — meaning that engineering-oriented metallurgists and ceramicists were not strongly connected to the theoretical advances in quantum mechanics and statistical mechanics that, in retrospect, were directly relevant to their problems, but without a different eye on the paper sheet. 

One example can be filled deliberately, is within the organic and inorganic chemistry of which came into an ever-increasing conflict throughout the nineteenth century, and "indeed as recently as 1969 an eminent British chemist was quoted as asserting that 'inorganic chemistry is a ridiculous field'". Both sides are rather deliberately correct on their own, and far wrong on the others, with understanding of what was going on internally of the synthesis of compounds and compositional analysis, specifically on carbon-based structures of organic chemistry and the possibility of the lack thereof, from the inorganic one, remained bedevilled by a number of confusions, "for instance, between gaseous atoms and molecules, the absence of such concepts as stereochemistry and isomerism". Even right now, the **scale problem** is particularly absent, to say that chemistry itself did not organize the field within scales and frames in which operatives from foundational primitives are sufficed to characterize which phenomena belong to where, and of what precursor that gives rise to such process, either multi-layer leaks on local-global interaction or not. Unsurprisingly, during such period, there was no agreed atomic theory, and even uncertainty about atomic weights, especially the inorganic elements. Even by now, such problem remains in practice of interaction, as for while there exists the standard model, interactions and dynamics of **nuclear physics** largely depends on a rather unpleasant proliferation of concepts and pluralism of patchwork models, that is used to understand nucleic interactions and productions. 

___

Another thing to note, lies rather in the physics itself. During the earlier development of metallurgy, during the 1920s, for example with Frenkel's paper [@frenkel1926shear], established what was then known as the **plastic deformation paradox**. Within such, Frenkel estimated the stress required to slide one atomic plane over another in a **perfect lattice** and thus gave
$$
\tau_{ideal}\approx \frac{G}{2\pi}
$$
where $G$ is the shear modulus. For typical metals, this gives $\tau_{ideal}\sim 10^{-1}G$, however, experimental yield stresses were typically $\tau_{exp}\sim 10^{-4}G$. Thus, there exists the discrepancy of the theory itself, and what the experiment gives. By the late 1920s, the discrepancy between theory and experiment of such was widely recognized in crystal physics and metallurgy, for which it is rather troubling because the predictions stemming from such rather *suspiciously stable* theory can be catastrophically wrong. Such stemmed the efforts made by which is the recognition for **dislocation theory**, for the specifically jointed tension effort by [@orowan1934plastic], [@polanyi1934plastic], then [@taylor1934plastic] and empirically confirmed of the conjecture by [@Hirsch2006-HIRDOO-2].  where one posits that plastic deformation occurs through *line defects* than uniform sliding of entire planes. Essentially turning them to local (relatively) events. More specifically, it reframes the entire stress deformation as

> A dislocation is a linear crystallographic defect whose motion allows atoms to slide at low stress.

And then, such was used throughout for the theory itself. However, even within such, inconsistency remains between continuum plasticity theory and microscopic dislocation dynamics. This is partially because the *interpretation apparatus considered of those structures* and theories are entangled, for one is concerned with smooth fields condensation for deformation on continuum, and one defines them via discrete avalanche-like events. The dislocation theory itself carries its fair share of paradox, for example, the **paradox of strength and ductility**, per [@valiev2002paradox], for which refers to the difficulty of achieving both high strength and high ductility in materials. A rather more catastrophic one is the *Frank-Read source*, for which is the mechanism for generation of multiple dislocation in well-spaced slip planes in crystalline structures, under deformation. Even with a recent 2024 papers, they only demonstrated the aspect of empirical deformation under multiplication dislocations. The issue remains that a perfect crystal, initially contains very few dislocations, yet during plastic deformation gives huge density of such. So, where do dislocations come from? Such require jumping outside the framework itself, of which then arguably confusing as to question its own ontology. Which might as well never work. Such also brings about the recent (quite so?) discovery of the **severe plastic deformation paradox**, which can be seen in [@valiev2003paradoxes], and persisted ever since. 

___

Within such systematic decoupling, of the academic field and the industry, the alignment of interests and system default, it is rather not surprising to see the developments failed in a way or another. While one party goes on one way, the other emphasizes another aspect of such. While Bell Laboratory, and many powerhouses of industrial research purposes were given freedom and exploratory merits that feed back to the grinding halt of the private proprietary claims, the other side is largely institutional, fragmented, argued of each other while given no quarter for actual communication and coherence of analysis. Academic tradition was often considered building knowledge for its own sake, organized around disciplinary identity and themed discussion, not allowing for anything else than internal peer recognition and specialties of identity, while the industrial one *forgone* any kind of theoretical scientific notion, in pursuits of empirical but successful products. The only problem at that point, is the lack of communication between the two, and the internal problem that crippled dialogues from within. 

When Sputnik launched in October 4th, 1957, the dialogue switched dramatically into overdrive. It is by then observed of those under administration roles to see of such dilemma, insufficient understanding of materials represented of the 1950s directly to a strategic shortcoming. We do have novel material per se, we do have many wonderful architectural designs. But we do not have a coherent theory, a stable framework, or any form of practical identification or practical theory of sort. Materials Advisory Board's 1967 report outlined some of such - characterization of material is a bottleneck (and may right now still be within its large complex structures without structural conditions), material construction identification is also a problem, effective theory and usage of materials of the time is mostly unknown, and perhaps furthermore, the practical-theoretical gap is strictly hierarchical officially - where practical knowledges serve to be the second-order of what of the constitution. Utilizing such, the response was framed by specific ideological commitment, of which [@ModyMartin2020_MaterialsScience] specified and identified as decisive - many scientists, most specifically American-Western scientists of physics in general, valorized 'pure science' and sought to distant themselves from such practical outcomes of their work. Physicists, those of whom are apart from the realization in the physical world, convinced the administrators and generals that engineering is not there sufficient anymore, such is to say paving way for the physics to be of higher-order, and metallurgy, production science, plastic science, to be simply not capable. This, is rather a self-serving framing for physicists - it positioned physics as master science that would redeem the backward engineering fields. That said, the most productive materials research of the preceding decades had come not from physicists imposing their framework on metallurgists and those manufacturing of their own practical devices, but to get the environment similar to *Bell Labs*, where there exists no clear hierarchy rather than the instantiation thereof, of the distance to be none, that a singular problem can be argued from both side and work on the same range, without the relationship being hierarchical. Such explains of the interdisciplinary failures, the failure of cumulative pluralism, **internal disciplinary acceptance** of which is rather counterproductive on its own, and the rigidity of expression and backward incompatibility the field inherited parts of. 

### To the present day

This section is here for now only to serve as the self-serving opening to the next sections. That is rather trivial, because we aim toward clarify the problems inherent of the current structures. Those, and of the fragmentation we would be seeing, came from a long line of slow decays, most often than not the fault of, or not, of the field itself. 

